# Site
name: "Surrounded by Giants"
description: "Science, Community and Stories"
meta_description: "Stories, interviews and personal experiences about and from the members of Open Science Community."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /surrounded-by-giants
google_analytics: 'UA-134359332-1' #'UA-46278016-1'
disqus: 'surroundedbygiants' #'demowebsite'
include: ["_pages"]
permalink: /:title/
contact: 'email.surroundedbygiants@gmail.com'

#mailchimp-list: '' #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  sharan:
    name: Malvika Sharan
    display_name: MalvikaSharan
    gravatar: 161196cf47af0d0c5873319fe90a7109
    email: email.surroundedbygiants@gmail.com
    web: https://malvikasharan.github.io/surrounded-by-giants
    twitter: https://twitter.com/MalvikaSharan
    description: "Author of Surrounded by Giants."
  davey:
    name: Norman Davey
    display_name: NormanDavey
    gravatar: 161196cf47af0d0c5873319fe90a7109
    email: email.surroundedbygiants@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/DaveyLab
    description: "contributor of Surrounded by Giants."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
