# Site
name: "Surrounded by Giants"
description: "Open Science, Community Building and Other Stories"
meta_description: "I sometimes write stuff."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blogs/
google_analytics: 'UA-134359332-1' #'UA-46278016-1'
include: ["_pages"]
permalink: /:title/

#mailchimp-list: '' #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  sharan:
    name: Malvika Sharan
    display_name: MalvikaSharan
    gravatar: malvikasharan9d39817158
    web: https://malvikasharan.github.io
    twitter: https://twitter.com/MalvikaSharan
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
